# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (C) 2023 VeriSilicon Holdings Co., Ltd.
#

ifdef CONFIG_TARGET_X5
obj-y += cpu.o
obj-y += x5_board.o
obj-y += x5_efuse.o
obj-y += fdt_setup.o
obj-y += boot_info.o
endif
