obj-$(CONFIG_X5_SEAMLESS_DISPLAY) += x5_display.o x5_output_dsi.o common/ dsi/ bridge/ dc8000/ backlight/ clock/
obj-$(CONFIG_VIDEO_X5_HDMI) += x5_output_hdmi.o x5_bt1120_soc.o hdmi/
obj-$(CONFIG_VIDEO_X5_PANEL_DSI) += panel/
